// ---------------------------------------------------------------------------
// Shared k8o base files — identical across the `library` and `web` templates.
// Template-specific files (pnpm-workspace, tsconfig, vite.config, CI, renovate)
// live in ./library.ts and ./web.ts.
// ---------------------------------------------------------------------------

export type GenerateOptions = {
  name: string;
  description?: string | undefined;
};

/** Derive repo coordinates from a (possibly scoped) package name. */
export const coords = (name: string): { bare: string; repo: string } => {
  if (!/^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/u.test(name)) {
    throw new Error(
      `Invalid package name "${name}" — expected an (optionally @scoped) npm package name.`,
    );
  }
  const bare = name.replace(/^@[^/]+\//u, '');
  return { bare, repo: `k35o/${bare}` };
};

export const NPMRC = `registry=https://registry.npmjs.org/
@k8o:registry=https://registry.npmjs.org/

engine-strict=true
`;

export const GITIGNORE = `node_modules
dist
coverage
*.log
.DS_Store
*.tsbuildinfo
.env*
*.local
.vscode/*
!.vscode/extensions.json
settings.local.json
`;

export const MISE_TOML = `[tools]
node = "24.16.0"
pnpm = "11.5.1"
`;

export const INSTALL_ACTION = `name: Install
description: Sets up mise and runs install

runs:
  using: composite
  steps:
    - name: Setup mise
      uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
      with:
        cache: true

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
`;

export const RELEASE_YML = `name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: \${{ github.workflow }}-\${{ github.ref }}

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          app-id: \${{ secrets.K35O_BOT_APP_ID }}
          private-key: \${{ secrets.K35O_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          token: \${{ steps.generate-token.outputs.token }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Create release Pull Request or publish to NPM
        uses: changesets/action@6a0a831ff30acef54f2c6aa1cbbc1096b066edaf # v1.7.0
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: \${{ steps.generate-token.outputs.token }}
`;

export const CHANGESET_README = `# Changesets

Hello and welcome! This folder has been automatically generated by \`@changesets/cli\`, a build tool that works with multi-package repos, or single-package repos to help you version and publish your code. You can find the full documentation for it [in our repository](https://github.com/changesets/changesets).

We have a quick list of common questions to get you started engaging with this project in [our documentation](https://github.com/changesets/changesets/blob/main/docs/common-questions.md).
`;

export const LICENSE = `MIT License

Copyright (c) k8o

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;

export const changesetConfig = (repo: string): string => `{
  "$schema": "https://unpkg.com/@changesets/config@3.1.1/schema.json",
  "changelog": ["@changesets/changelog-github", { "repo": "${repo}" }],
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "public",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
`;
